### ISSUE TITLE
Refined Storage/Nuclearcraft - Unable to autocraft Basic Plating

### ISSUE THREAD

**Issue by Lance8773** [al132mc/antimatter-chemistry#264]
Hello, I have been hosting a personal dedicated server for a friend and I and have recently encountered a slight issue. When I attempted to autocraft Nuclearcraft Basic Plating with Refined Storage I encountered an error message and was not able to proceed with the craft. I at first thought it was resources, but then made sure that all of the reagents were craftable by doing so manually. I then thought it may be the Storage Reborn Multi-block crafter, but moving the pattern to a regular crafter did not fix it either. Lastly I attempted to make a processing pattern and have the resources go to a mechanical crafter to see if that would work but that had no success either. I looked at the server logs after and it appears that the basic plating was essentially not registering as an item to refined storage if I'm correct (Not that versed in code, but this isn't hard to decipher). Is this a known bug, something specific to me, or other? Are there any solutions to fix this (Server restarts and things did not fix the issue)

Below are the Server logs immediately after attempting to craft the basic plating:

[15:45:02] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.IllegalStateException: Cannot have empty result
[15:45:02] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:       at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern.getOutput(CraftingPattern.java:201)
[15:45:02] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:       at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculateInternal(CraftingTask.java:536)
[15:45:02] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:       at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.calculate(CraftingTask.java:265)
[15:45:02] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:       at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.lambda$onCraftingPreviewRequested$0(ItemGridHandler.java:186)
[15:45:02] [RS crafting preview calculation/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:       at java.lang.Thread.run(Unknown Source)

**Comment by Lance8773** [comment]
This was apparently User error on my part (ish). This recipe doesn't work with Ore-Dict on, but works fine with Ore-Dict off. (Thought I had tried that before posting but I guess not? :P)
